# Generated by Django 2.2.25 on 2021-12-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('script', models.CharField(max_length=50)),
                ('terminal', models.CharField(max_length=5000)),
                ('data', models.DateTimeField()),
                ('error', models.CharField(max_length=5000)),
            ],
        ),
    ]
